name: Release
run-name: Release ${{ github.ref_name }}

# TODO:tom real workflow trigger
on:
  workflow_dispatch:

env:
  JAVA_VERSION: 17

jobs:
  # --------------------------------------------------
  # job: assemble
  # --------------------------------------------------
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # setup steps
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          architecture: x64
          cache: gradle

      # build steps
      - name: Compile
        run: make distribution

      # upload steps
      - name: Upload artifacts (libs)
        uses: actions/upload-artifact@v4
        with:
          retention-days: 3
          name: libs
          path: modules/*/build/libs/

      - name: Upload artifacts (distribution)
        uses: actions/upload-artifact@v4
        with:
          retention-days: 3
          name: distribution
          path: build/releases/

      - name: Upload artifacts (plugins)
        uses: actions/upload-artifact@v4
        with:
          retention-days: 3
          compression-level: 0
          name: plugins
          path: |
            plugins/build/libs/
            plugins/*/build/libs/

  # --------------------------------------------------
  # job: deploy-maven
  # --------------------------------------------------
  deploy-maven:
    name: Deploy to Maven
    runs-on: ubuntu-latest
    needs: assemble
    timeout-minutes: 15
    steps:
      # setup steps
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          architecture: x64
          cache: gradle

      - name: Download artifacts (libs)
        uses: actions/download-artifact@v4
        with:
          name: libs
          path: modules

      # deploy step
      - name: Deploy to maven
        run: bash .github/scripts/deploy-to-maven.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          MAVEN_PUBLISH_URL: ${{ vars.MAVEN_PUBLISH_URL }}

  # --------------------------------------------------
  # job: deploy-s3
  # --------------------------------------------------
  deploy-s3:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: assemble
    timeout-minutes: 15
    steps:
      # setup steps
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}

      - name: Download artifacts (distribution)
        uses: actions/download-artifact@v4
        with:
          name: distribution
          path: build/releases

      # deploy step
      - name: Deploy to S3
        run: bash .github/scripts/deploy-to-s3.sh
        env:
          S3_RELEASE_BUCKET: ${{ vars.S3_RELEASE_BUCKET }}

  # --------------------------------------------------
  # job: deploy-docker
  # --------------------------------------------------
  deploy-docker:
    name: Deploy to Docker
    runs-on: ubuntu-latest
    needs: assemble
    timeout-minutes: 15
    steps:
      # setup steps
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to Seqera registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.SEQERA_PUBLIC_CR_URL }}
          username: ${{ secrets.SEQERA_PUBLIC_CR_USER }}
          password: ${{ secrets.SEQERA_PUBLIC_CR_PASSWORD }}

      # deploy step
      - name: Deploy to docker
        run: bash .github/scripts/deploy-to-docker.sh
        env:
          SEQERA_REGISTRY: ${{ vars.SEQERA_PUBLIC_CR_URL }}

  # --------------------------------------------------
  # job: deploy-plugins
  # --------------------------------------------------
  deploy-plugins:
    name: Deploy Plugins
    runs-on: ubuntu-latest
    needs: assemble
    timeout-minutes: 15
    steps:
      # setup steps
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          architecture: x64
          cache: gradle

      - name: Download artifacts (plugins)
        uses: actions/download-artifact@v4
        with:
          name: plugins
          path: plugins

      # deploy steps
      - name: Deploy plugins to maven
        run: bash .github/scripts/deploy-plugins-to-maven.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          MAVEN_PUBLISH_URL: ${{ vars.MAVEN_PLUGINS_PUBLISH_URL }}

      - name: Deploy plugins to github
        run: bash .github/scripts/deploy-plugins-to-github.sh
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          GH_ORG: ${{ vars.PLUGINS_GITHUB_ORG }}

      - name: Update plugins index
        run: bash .github/scripts/update-plugins-index.sh
        env:
          GH_ORG: ${{ vars.PLUGINS_GITHUB_ORG }}
          GH_USER: ${{ vars.DEPLOY_GITHUB_USER }}
          GH_USER_EMAIL: ${{ vars.DEPLOY_GITHUB_EMAIL }}
          GH_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          PLUGINS_INDEX_JSON: ${{ vars.PLUGINS_INDEX_JSON }}
